const grids = [
    {
        id:1156,
        titre: "minifleches_0_1556",
        legende: "",
        force: "3",
        nbcaseslargeur: 6,
        nbcaseshauteur: 8,
        grille: [
            "wGmEkA",
            "CUITES",
            "qEMANA",
            "ARPfCD",
            "rROSEb",
            "PILANT",
            "qEIaSE",
            "ARETES"],
        definitions: [
            ["HOMME", "EN", "CONFLIT"],
            ["LIVRÉES", "AU FEU"],
            ["CARAC–", "TÈRE", "ÉTRANGER"],
            ["DISCOUR–", "TOISE"],
            ["LAC DE", "SYRIE"],
            ["CHÈRE–", "MENT", "LOUÉ"],
            ["SE", "DÉGAGEA"],
            ["PEINTRE", "DADAÏSTE"],
            ["DISQUE", "LASER"],
            ["SOCIÉTÉ", "PAR", "ACTIONS"],
            ["COULEUR", "DE LA", "BELLE VIE"],
            ["ÉCRASANT"],
            ["ADJECTIF", "POSSESSIF", "PLURIEL"],
            ["UN PEU", "D'ÉMOI"],
            ["OS DE", "BARBUE"],
            ["FORME", "LE PRONO–", "MINAL"]
        ],
        spountzV: [[5, 4]],
        spountzH: [[4, 5]],
        photos: [],
        concours: [],
        enonceconcours: ""
    },
    {
        id:1155,
        titre: "minifleches_0_1555",
        legende: "",
        force: "3",
        nbcaseslargeur: 6,
        nbcaseshauteur: 8,
        grille: [
            "wMkMkC",
            "TIQUER",
            "rNURSE",
            "NIEMEN",
            "dJaURE",
            "PUERIL",
            "dPaENE",
            "SENSEE"],
        definitions: [
            ["COURTE", "TENUE DE", "COURT"],
            ["RECHI–", "GNER"],
            ["MESSES", "BASSES"],
            ["PRONOM", "INTERRO–", "GATIF"],
            ["DOTÉE DE", "CRANS"],
            ["ELLE AGIT", "SUR LA", "PUPILLE"],
            ["BONNE", "D'EN–", "FANTS"],
            ["FLEUVE", "D'EUROPE"],
            ["QUI EST", "RESTÉ", "TRÈS", "JEUNE"],
            ["BŒUF QUI", "N'EST", "PLUS À", "LA MODE"],
            ["QUI A LA", "RAISON", "POUR", "ELLE"],
            ["DIRECTION", "SUR LA", "BOUSSOLE"]
        ],
        spountzV: [[5, 7], [4, 7]],
        spountzH: [],
        photos: [],
        concours: [],
        enonceconcours: ""
    },
    {
        id:1154,
        titre: "minifleches_0_1554",
        legende: "",
        force: "3",
        nbcaseslargeur: 6,
        nbcaseshauteur: 8,
        grille: [
            "wAlLlS",
            "ADROIT",
            "rJEUNA",
            "ZAPPER",
            "qCEaDI",
            "MENAIS",
            "qNSaTE",
            "STEREE"],
        definitions: [
            ["TEL UN", "ANGLE", "SUR PLAN"],
            ["LOIN DU", "MANCHE"],
            ["ANIMAL", "DE CONTE"],
            ["VU DIFFÉ–", "REMMENT"],
            ["TRÈS", "CÉLÈBRE"],
            ["JAMAIS", "VUE"],
            ["NE", "MANGEA", "PAS"],
            ["CHANGER", "DE CANAL"],
            ["SERT À", "DÉSIGNER"],
            ["ÉTAIS", "EN TÊTE"],
            ["CHEF DE", "DISTRICT"],
            ["INITIALES", "PIEUSES"],
            ["MESURÉE"],
            ["SUR LA", "TABLE", "DU DES–", "SINATEUR"]
        ],
        spountzV: [[2, 7]],
        spountzH: [],
        photos: [],
        concours: [],
        enonceconcours: ""
    },
    {
        id:1158,
        titre: "minifleches_0_1558",
        legende: "",
        force: "3",
        nbcaseslargeur: 6,
        nbcaseshauteur: 8,
        grille: [
            "xPmAlM",
            "HIPPIE",
            "rSALON",
            "MANANT",
            "qLETbI",
            "ILLICO",
            "dEaEON",
            "CRESUS"],
        definitions: [
            ["CE N'EST", "PAS LE", "CHOIX", "DU CŒUR"],
            ["BEATNIK"],
            ["ÉCRA–", "BOUIL–", "LÉES"],
            ["GROUPE À", "SONDER"],
            ["NOTES", "BRÈVES"],
            ["ATOME", "DÉNATURÉ"],
            ["BOUTIQUE", "DE", "MERLAN"],
            ["LE NOBLE", "EN FIT FI"],
            ["TERME DE", "SPORT"],
            ["INCONTI–", "NENT"],
            ["IL MONTE", "À LA TÊTE", "ET NOUS", "LA FAIT", "TOURNER"],
            ["ROI À LA", "FORTUNE", "LÉGEN–", "DAIRE"],
            ["CHEVA–", "LIER", "AMBIGU", "NÉ À TON–", "NERRE (D')"]
        ],
        spountzV: [],
        spountzH: [[2, 3]],
        photos: [],
        concours: [],
        enonceconcours: ""
    },
    {
        id:1159,
        titre: "minifleches_0_1559",
        legende: "",
        force: "3",
        nbcaseslargeur: 6,
        nbcaseshauteur: 8,
        grille: [
            "wDlTlA",
            "HASARD",
            "qTAREE",
            "SALIEN",
            "pTENDb",
            "MIRfIP",
            "dOaOTS",
            "ANISAT"],
        definitions: [
            ["ACTION AU", "CARBONE", "14"],
            ["IL A SES", "CAPRICES"],
            ["PIF"],
            ["DONNER", "DU GOÛT"],
            ["VILLE DU", "YÉMEN"],
            ["RÉIM–", "PRIMA"],
            ["PESÉE"],
            ["ANCIEN", "FRANC"],
            ["ALLONGE", "LE BRAS"],
            ["ELLE", "TOURNAIT", "EN L'AIR"],
            ["POUR", "APPELER", "SANS SE", "FAIRE RE–", "MARQUER"],
            ["ADRESSE", "DU PC"],
            ["IL EST", "BIEN EN", "CHAIR"],
            ["PARFUMÂT", "À LA PRO–", "VENÇALE"],
            ["LA FIN DES", "HARICOTS"]
        ],
        spountzV: [[5, 6]],
        spountzH: [],
        photos: [],
        concours: [],
        enonceconcours: ""
    }
]

const enumCaseType = {
    All: 1,
    Letter: 2,
    Description: 3,
    Empty: 4
};

var enumArrow = {
    Right: 0,
    RightBottom: 1,
    Bottom: 2,
    BottomRight: 3
};

export { grids, enumCaseType, enumArrow };