# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: Deno

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Deploy React to GitHub Pages
        # You may pin to the exact commit or the version.
        # uses: bitovi/github-actions-react-to-github-pages@4047c7f17e90e86c4daf2d49befd066f504df07c
        uses: bitovi/github-actions-react-to-github-pages@v1.2.1
